

// DIRECT RUDUX
export const SELECT_WORK_DATA   = 'SELECT_WORK_DATA';
export const SELECT_WORK_DATA_SUCCESS = 'SELECT_WORK_DATA_SUCCESS';
export const SELECT_WORK_DATA_NODATA = 'SELECT_WORK_DATA_NODATA';

export const REDUCER_SET_USER_CONNECTION   = 'REDUCER_SET_USER_CONNECTION';
export const REDUCER_SET_USER_DATA   = 'REDUCER_SET_USER_DATA';

// SAGA
export const INSERT_NEW_USER_IN_DB_TYPE   = 'INSERT_NEW_USER_IN_DB_TYPE';
export const SELECT_USER_CONNECTION_TYPE   = 'SELECT_USER_CONNECTION_TYPE';
export const SELECT_USER_INFO_ACTION_TYPE   = 'SELECT_USER_INFO_ACTION_TYPE';

export const PUT_USER_INFO_ACTION_TYPE      = 'PUT_USER_INFO_ACTION_TYPE';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const IS_LOADING = 'is loading...';
